(function(){
let stats={encryptions:847,decryptions:812,sessionsCreated:36,sessionsDestroyed:12,activeSessions:24};
let currentSessionId=1;
let lastTransaction=null;
let lastEnvelope=null;
function updateAllStats(){document.getElementById('statEnc')&&(document.getElementById('statEnc').innerText=stats.encryptions);document.getElementById('statDec')&&(document.getElementById('statDec').innerText=stats.decryptions);document.getElementById('statSessions')&&(document.getElementById('statSessions').innerText=stats.sessionsCreated);document.getElementById('statActive')&&(document.getElementById('statActive').innerText=stats.activeSessions);document.getElementById('liveEnc')&&(document.getElementById('liveEnc').innerText=stats.encryptions);document.getElementById('liveDec')&&(document.getElementById('liveDec').innerText=stats.decryptions);document.getElementById('liveSessCreated')&&(document.getElementById('liveSessCreated').innerText=stats.sessionsCreated);document.getElementById('liveActive')&&(document.getElementById('liveActive').innerText=stats.activeSessions);}
function showToast(msg,isError=false){let toast=document.createElement('div');toast.innerText=msg;toast.style.position='fixed';toast.style.bottom='30px';toast.style.left='50%';toast.style.transform='translateX(-50%)';toast.style.backgroundColor=isError?'#6a2c2c':'#0b1428';toast.style.color='#ebf2ff';toast.style.padding='12px 28px';toast.style.borderRadius='60px';toast.style.fontFamily="'JetBrains Mono',monospace";toast.style.fontSize='0.75rem';toast.style.border='1px solid #2f5280';toast.style.zIndex='1000';toast.style.backdropFilter='blur(8px)';document.body.appendChild(toast);setTimeout(()=>toast.remove(),3000);}
function simulateEncryption(){stats.encryptions++;stats.decryptions++;updateAllStats();showToast('AES-256-GCM ENCRYPTED | TAG VERIFIED | IV: 0x'+Math.random().toString(16).substr(2,12));}
function simulateCreateSession(){if(stats.activeSessions<32){stats.sessionsCreated++;stats.activeSessions++;currentSessionId=stats.sessionsCreated;updateAllStats();showToast(`SESSION CREATED | ID: ${currentSessionId} | TTL: 3600s | KEY: PBKDF2×100k`);}else{showToast('MAX SESSIONS REACHED (32) | DESTROY INACTIVE FIRST',true);}}
function simulateDestroySession(){if(stats.activeSessions>0){stats.activeSessions--;stats.sessionsDestroyed++;updateAllStats();showToast('SESSION DESTROYED | bank_secure_zero() EXECUTED | KEYS WIPED');}else{showToast('NO ACTIVE SESSIONS TO DESTROY',true);}}
function resetStats(){stats={encryptions:0,decryptions:0,sessionsCreated:0,sessionsDestroyed:0,activeSessions:0};updateAllStats();showToast('STATS RESET | MASTER KEY ROTATED | MEMORY SCRUBBED');}
function createTransaction(){let from=document.getElementById('txFrom')?.value||'0xA1B2C3D4E5F67890';let to=document.getElementById('txTo')?.value||'0x9876543210FEDCBA';let amount=document.getElementById('txAmount')?.value||1000000;let currency=document.getElementById('txCurrency')?.value||'USD';let txId=Date.now();let timestamp=Math.floor(Date.now()/1000);let nonce=Math.floor(Math.random()*0xFFFFFFFFFFFFFFFF);let signature=Array(32).fill(0).map(()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join('');let refHash=Array(32).fill(0).map(()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join('');lastTransaction={transaction_id:txId,timestamp:timestamp,from_account:from,to_account:to,amount:Number(amount),currency:currency,nonce:nonce,signature:signature,reference_hash:refHash,verified:1};let output=`TRANSACTION CREATED\nID: ${txId}\nFROM: ${from.substring(0,16)}...\nTO: ${to.substring(0,16)}...\nAMOUNT: ${amount} ${currency}\nSIGNATURE: ${signature.substring(0,32)}...\nNONCE: ${nonce}\nREF HASH: ${refHash.substring(0,32)}...`;document.getElementById('txOutput')&&(document.getElementById('txOutput').innerHTML=`<pre>${output}</pre>`);stats.encryptions++;updateAllStats();showToast(`TRANSACTION ${txId} CREATED | SIGNED WITH HMAC-SHA256`);}
function verifyTransaction(){if(lastTransaction){let valid=Math.random()>0.1;if(valid){showToast(`TRANSACTION ${lastTransaction.transaction_id} VERIFIED | SIGNATURE OK | REF_HASH MATCH`);if(document.getElementById('txOutput')){let out=document.getElementById('txOutput');out.innerHTML=out.innerHTML+'<br><span style="color:#6fcf97;">✓ VERIFICATION PASSED</span>';}}else{showToast(`TRANSACTION ${lastTransaction.transaction_id} VERIFICATION FAILED | TAG MISMATCH`,true);if(document.getElementById('txOutput')){let out=document.getElementById('txOutput');out.innerHTML=out.innerHTML+'<br><span style="color:#e74c3c;">✗ VERIFICATION FAILED</span>';}}}else{showToast('NO TRANSACTION CREATED',true);}}
function createEnvelope(){let timestamp=Math.floor(Date.now()/1000);let crc32=0xFFFFFFFF;let authTag=Array(32).fill(0).map(()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join('');let iv=Array(12).fill(0).map(()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join('');let tag=Array(16).fill(0).map(()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join('');lastEnvelope={timestamp:timestamp,crc32:crc32,auth_tag:authTag,iv:iv,tag:tag,version:2,encrypted_len:128};let output=`SECURE ENVELOPE CREATED\nVERSION: 2\nTIMESTAMP: ${timestamp}\nCRC32: 0x${crc32.toString(16)}\nAUTH TAG: ${authTag.substring(0,32)}...\nIV: ${iv}\nGCM TAG: ${tag}`;document.getElementById('envOutput')&&(document.getElementById('envOutput').innerHTML=`<pre>${output}</pre>`);stats.encryptions++;updateAllStats();showToast('ENVELOPE CREATED | auth_tag BOUND TO SESSION KEY');}
function extractEnvelope(){if(lastEnvelope){let success=Math.random()>0.1;if(success){showToast('ENVELOPE EXTRACTED | CRC32 VERIFIED | AUTH_TAG MATCH | DECRYPTED');if(document.getElementById('envOutput')){let out=document.getElementById('envOutput');out.innerHTML=out.innerHTML+'<br><span style="color:#6fcf97;">✓ ENVELOPE EXTRACTED SUCCESSFULLY</span>';}}else{showToast('ENVELOPE TAMPERED | CRC32 MISMATCH | AUTHENTICATION FAILED',true);if(document.getElementById('envOutput')){let out=document.getElementById('envOutput');out.innerHTML=out.innerHTML+'<br><span style="color:#e74c3c;">✗ EXTRACTION FAILED</span>';}}}else{showToast('NO ENVELOPE CREATED',true);}}
document.getElementById('btnEncrypt')?.addEventListener('click',simulateEncryption);
document.getElementById('btnSession')?.addEventListener('click',simulateCreateSession);
document.getElementById('btnDestroy')?.addEventListener('click',simulateDestroySession);
document.getElementById('btnReset')?.addEventListener('click',resetStats);
document.getElementById('btnCreateTx')?.addEventListener('click',createTransaction);
document.getElementById('btnVerifyTx')?.addEventListener('click',verifyTransaction);
document.getElementById('btnCreateEnv')?.addEventListener('click',createEnvelope);
document.getElementById('btnExtractEnv')?.addEventListener('click',extractEnvelope);
document.querySelectorAll('.nav-link').forEach(btn=>{btn.addEventListener('click',()=>{let pageId=btn.getAttribute('data-page');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-link').forEach(n=>n.classList.remove('active'));btn.classList.add('active');let target=document.getElementById(pageId);if(target)target.classList.add('active');if(window.innerWidth<=820){document.getElementById('sidebar')?.classList.remove('mobile-open');}});});
let menuBtn=document.createElement('div');menuBtn.className='menu-toggle';menuBtn.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="white" width="28" height="28"><path d="M3 12h18M3 6h18M3 18h18"/></svg>';menuBtn.addEventListener('click',()=>{document.getElementById('sidebar')?.classList.toggle('mobile-open');});if(document.querySelector('.app')&&!document.querySelector('.menu-toggle')){document.querySelector('.app').appendChild(menuBtn);}
updateAllStats();
console.log('BLACKSTONE v3.0 | CONSTANT-TIME ACTIVE | MEMORY SCRUBBER READY');
})();
